#!/bin/bash
if [[ -a /etc/mercury/server_tuneables ]]; then
. /etc/mercury/server_tuneables
fi

RAM=`grep MemTotal /proc/meminfo | sed 's/[^0-9]*//g'`

if [[ -n "$APACHE_MAXCLIENTS" ]]; then
   echo "$APACHE_MAXCLIENTS"
elif (($RAM>=8000000)); then
    echo "80"
elif (($RAM>=4000000)); then
    echo "40"
elif (($RAM>=2000000)); then
    echo "20"
elif (($RAM>=1000000)); then
    echo "10"
else
    echo "5"
fi
