#!/bin/bash
if [[ -a /etc/mercury/server_tuneables ]]; then
. /etc/mercury/server_tuneables
fi

RAM=`grep MemTotal /proc/meminfo | sed 's/[^0-9]*//g'`

if [[ -n "$APC_MEMORY" ]]; then
   echo "$APC_MEMORY"
elif (($RAM>=8000000)); then
    echo "256"
elif (($RAM>=4000000)); then
    echo "256"
elif (($RAM>=2000000)); then
    echo "256"
elif (($RAM>=1000000)); then
    echo "128"
elif (($RAM>=500000)); then
    echo "96"
else
    echo "96"
fi

