#!/bin/bash
if [[ -a /etc/mercury/server_tuneables ]]; then
. /etc/mercury/server_tuneables
fi

RAM=`grep MemTotal /proc/meminfo | sed 's/[^0-9]*//g'`

if [[ -n "$TOMCAT_MAX_THREADS" ]]; then
   echo "$TOMCAT_MAX_THREADS"
elif (($RAM>=8000000)); then
    echo "40"
elif (($RAM>=4000000)); then
    echo "20"
elif (($RAM>=2000000)); then
    echo "10"
elif (($RAM>=1000000)); then
    echo "6"
else
    echo "3"
fi
